### ISSUE TITLE
Add some automation to release new versions of the lib

### ISSUE THREAD

**Issue by carloscasalar** [carloscasalar/traveller-npc-generator#14]
This project is at the same time a CLI command and a go lib. I'm writing changes in a CHANGELOG by hand. I want to automate the release so when I merge a branch where I introduced a new version in the CHANGELOG a new version is tagged and used its descriptions as the release notes. I also want to check all this is fine before merge to avoid merges where the tagging of the new version fails

**Comment by carloscasalar** [comment]
## Copilot advice

To achieve automated releases with validation for your Go project, follow these steps:

### Step 1: Setup Automated Release Workflows
1. **Create a GitHub Actions workflow for tagging a new version**:
    - This workflow will trigger when changes to the CHANGELOG are merged.
2. **Create a GitHub Actions workflow to publish release notes**:
    - This workflow will extract the version description from the CHANGELOG and use it as the release notes.

### Step 2: Setup Pre-Merge Validation
1. **Add a GitHub Actions workflow to validate the CHANGELOG format and versioning**:
    - This ensures the tagging process will not fail.
2. **Configure required status checks**:
    - Ensure that the validation workflow must pass before a branch can be merged.

I will now create the necessary GitHub Actions workflows for you.Let's start by creating the necessary GitHub Actions workflows.

### Step 1: Setup Automated Release Workflows

1. Create a GitHub Actions workflow for tagging a new version when changes to the CHANGELOG are merged:
   - Create a file at `.github/workflows/tag-release.yml` with the following content:
     ```yaml
     name: Tag Release

     on:
       push:
         branches:
           - main

     jobs:
       tag:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout code
             uses: actions/checkout@v2

           - name: Set up Go
             uses: actions/setup-go@v2
             with:
               go-version: '1.17'

           - name: Get version from CHANGELOG
             id: changelog
             run: |
               VERSION=$(grep -m1 -oP '(?<=## )[^ ]+' CHANGELOG.md)
               echo "::set-output name=version::$VERSION"
               echo "Version: $VERSION"

           - name: Create Tag
             run: |
               git tag ${{ steps.changelog.outputs.version }}
               git push origin ${{ steps.changelog.outputs.version }}
     ```

2. Create a GitHub Actions workflow to publish release notes from the CHANGELOG:
   - Create a file at `.github/workflows/publish-release.yml` with the following content:
     ```yaml
     name: Publish Release

     on:
       push:
         tags:
           - '*'

     jobs:
       release:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout code
             uses: actions/checkout@v2

           - name: Set up Go
             uses: actions/setup-go@v2
             with:
               go-version: '1.17'

           - name: Get release notes from CHANGELOG
             id: changelog
             run: |
               VERSION=${{ github.ref }}
               NOTES=$(awk '/^## $VERSION/{flag=1;next}/^## /{flag=0}flag' CHANGELOG.md)
               echo "::set-output name=notes::$NOTES"

           - name: Publish Release
             uses: actions/create-release@v1
             with:
               tag_name: ${{ github.ref }}
               release_name: ${{ github.ref }}
               body: ${{ steps.changelog.outputs.notes }}
               draft: false
               prerelease: false
     ```

### Step 2: Setup Pre-Merge Validation

1. Add a GitHub Actions workflow to validate the CHANGELOG format and versioning before merging the branch:
   - Create a file at `.github/workflows/validate-changelog.yml` with the following content:
     ```yaml
     name: Validate Changelog

     on:
       pull_request:
         branches:
           - main

     jobs:
       validate:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout code
             uses: actions/checkout@v2

           - name: Validate CHANGELOG format
             run: |
               if ! grep -qE '^## [0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md; then
                 echo "CHANGELOG format is incorrect"
                 exit 1
               fi
     ```

2. Configure required status checks on the GitHub repository settings to include the validation workflow.

Test the workflows by creating a pull request with changes to the CHANGELOG and observe if the tagging and release notes are generated correctly. Refine the workflows if necessary based on the initial tests and any errors encountered during execution.
